sudo: false
language: node_js
os:
    - linux
node_js:
    - "node"
install:
    - npm install
    - ./node_modules/bower/bin/bower install
    - ./node_modules/webpack/bin/webpack.js
    - find js ! -name "*.bundle.js" -exec rm {} \;
deploy:
    provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: cordea.jp
    skip_cleanup: true
